### ISSUE TITLE
Font Size problem

### ISSUE THREAD

**Issue by cicciopizza** [algenty/grafana-flowcharting#21] opened 2019-06-21 08:31 UTC
In draw.io i have these font size:
![Selezione_005](https://user-images.githubusercontent.com/26459829/59909187-6156a780-940f-11e9-97bb-240397e4717e.png)

after saving in graphana I have this:

![Selezione_006](https://user-images.githubusercontent.com/26459829/59909215-716e8700-940f-11e9-95a9-db81503a5e79.png)

**Comment by algenty** [comment] 2019-06-21 17:20
Hi cicciopizza,
What is your version ?

BG
Arnaud

**Comment by cicciopizza** [comment] 2019-06-21 19:07
Hi Arnaud,

I tried both with version 0.3.0 and version 0.40

I always have the same problem.





Grafana ver.  6.2.2







---- Attivato ven, 21 giu 2019 19:20:04 +0200 Arnaud GENTY <mailto:notifications@github.com> ha scritto ----


Hi cicciopizza,
 What is your version ?
BG
 Arnaud

**Comment by algenty** [comment] 2019-06-21 21:51
i have friend who have same problem but i cant reproduce it, can you give me xml definiton please ?

Bg

**Comment by cicciopizza** [comment] 2019-06-22 07:42
Hi
this is the XML:





<mxfile modified="2019-06-22T07:36:19.207Z" host="http://www.draw.io" agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36" version="10.8.0" etag="awDzsGtCehP3swmgaxHn"><diagram id="1456pSyEQyzJojISZvVK" name="Page-1">7ZRNU4MwEIZ/DUdngLTUHkutevFUZzxnyAIZA8EQCvXXuynLl9UZL3qSC8mzm93Nvgse2xfdg+FV/qQFKC/0ReexOy8MA7Zd4cuRc09uw3UPMiMFOU3gKN+BoE+0kQLqhaPVWllZLWGiyxISu2DcGN0u3VKtllkrnsEVOCZcXdMXKWw+3GIz8UeQWT5kDqJtbyn44Ew3qXMudDtD7OCxvdHa9qui24NyzRv60p+7/8Y6FmagtD86QIWduGrocl4YKTwbpxpDuB4qbS6W6K1xZcVeyNLUx2eO/NqeqT0DdAFu6ot4O3RY+1U3PxFl7v0MnR0yYpl90t5EHRrjhtb5sji3hUIQ4LK2Rr/CnkosdQkur1TqE+JKZiVuE2wLII9PYKxEQXdkKKQQLk3c5tLCseKJy9ni+CIzuikFuI75Y1kuAHTfdj0YtcSPAHQB1pzRhQ6wLclP87+mbTsN04pQPpujYWg4jW82Bp4UxgWJ/LXgQ4w/EHzzr/eoN1voHax+TXDcTn+Pi232D2aHDw==</diagram></mxfile>






Just to make sure you don't have other interfering plugins I just installed a scratch-free version of graphana:


Grafana v6.2.4 (commit: ee01897)



and then I installed the FlowCharting plugin with



sudo grafana-cli plugins install agenty-flowcharting-panel





Bg

Alfredo






---- Attivato ven, 21 giu 2019 23:51:12 +0200 Arnaud GENTY <notifications@github.com> ha scritto ----



i have friend who have same problem but i cant reproduce it, can you give me xml definiton please ?

Bg

**Comment by algenty** [comment] 2019-06-23 22:00
Hi,
First, thx again for your feedback
I dont know why but in your value in xml, i have 
value="&lt;font color=&quot;#ff0000&quot; style=&quot;font-size: 7px&quot;&gt;Text&lt;/font&gt;"

If i add text in in empty model, i have in xml : 
value="Text" and its works for me.

I need more test to understand why
![2019-06-23 23_57_09-Grafana - New dashboard](https://user-images.githubusercontent.com/47012725/59982446-c2020200-9612-11e9-8ea6-abe74de248f5.png)

Try this model : 
1Zbfb4IwEMf/Gh6XQGtUHoVNl+zHw3Rx2VtDT2gslNUq4F+/Iu2EkSWLDxvyQLhPr3e9+x4BB4dpuZAkT54EBe4gl5YOvnUQGmGk7zWoGjCZjhsQS0Yb5J3Bkh3BQNfQPaOw6zgqIbhieRdGIssgUh1GpBRF120jeDdrTmLogWVEeJ+uGVVJQ6docub3wOLEZvbGfrOSEutsKtklhIqihfCd486c+tl1cCiFUB1kF9IyBF731PariTf/nfPX+SVk6oL9b69o+x6s1kDxc+U/sofjy8eNCXogfG/atIJSmTJVZXunaoiDRKVcA08/7pQUWwgFF1KTTGTaM9gwzr8hwlmcaTPShwbNgwNIxbQqM7OQMkrrNEGRMAXLnER1zkKPoGZS7DMKdQFuHV5kyswVHhnbpnMQns9dfWneb5QtU+eGsoX6jTu3bwEiBSUrbZst2DcDYN6AkTGL8zhZlLQmyY4NMQMcfwX+UTzNjX6XS4uuVVr3X6TFHWn9QUuLr1RaNB6AtB4etLaja9UWDUHbyR9re+KtD77xa/1Bnfgn

**Comment by cicciopizza** [comment] 2019-06-24 07:56
Hi,

if I paste your xml model directly in grafana (flowchart) it works fine


If I click "Edit Draw" the model is imported into draw.io correctly





If in draw.io WITHOUT MAKING ANY CHANGE click on menu: Extra> Edit Diagram
I see this XML (which is correct:)





<mxGraphModel dx="754" dy="577" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="827" pageHeight="1169" math="0" shadow="0">

  <root>

    <mxCell id="0"/>

    <mxCell id="1" parent="0"/>

    <mxCell id="XU2kZBTWed3Ny9LiKzRq-1" value="Text" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;fontSize=34;fontColor=#FF0000;" parent="1" vertex="1">

      <mxGeometry x="390" y="40" width="40" height="20" as="geometry"/>

    </mxCell>

    <mxCell id="XU2kZBTWed3Ny9LiKzRq-2" value="Text" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;fontSize=30;fontColor=#FF0000;" parent="1" vertex="1">

      <mxGeometry x="393" y="90" width="40" height="20" as="geometry"/>

    </mxCell>

    <mxCell id="XU2kZBTWed3Ny9LiKzRq-3" value="Text" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;fontSize=26;fontColor=#FF0000;" parent="1" vertex="1">

      <mxGeometry x="393" y="130" width="40" height="20" as="geometry"/>

    </mxCell>

    <mxCell id="XU2kZBTWed3Ny9LiKzRq-4" value="Text" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;fontSize=22;fontColor=#FF0000;" parent="1" vertex="1">

      <mxGeometry x="393" y="170" width="40" height="20" as="geometry"/>

    </mxCell>

  </root>

</mxGraphModel>



If I edit (in draw.io) the last "Text" and modify ONLY Font Size to 72 pt and then Edit it (Menu Extra > Edit Diagram) 

I see this XML:



<mxGraphModel dx="754" dy="577" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="827" pageHeight="1169" math="0" shadow="0">

  <root>

    <mxCell id="0"/>

    <mxCell id="1" parent="0"/>

    <mxCell id="XU2kZBTWed3Ny9LiKzRq-1" value="Text" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;fontSize=34;fontColor=#FF0000;" parent="1" vertex="1">

      <mxGeometry x="390" y="40" width="40" height="20" as="geometry"/>

    </mxCell>

    <mxCell id="XU2kZBTWed3Ny9LiKzRq-2" value="Text" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;fontSize=30;fontColor=#FF0000;" parent="1" vertex="1">

      <mxGeometry x="393" y="90" width="40" height="20" as="geometry"/>

    </mxCell>

    <mxCell id="XU2kZBTWed3Ny9LiKzRq-3" value="Text" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;fontSize=26;fontColor=#FF0000;" parent="1" vertex="1">

      <mxGeometry x="393" y="130" width="40" height="20" as="geometry"/>

    </mxCell>

    <mxCell id="XU2kZBTWed3Ny9LiKzRq-4" value="&lt;font style=&quot;font-size: 72px&quot;&gt;Text&lt;/font&gt;" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;fontSize=22;fontColor=#FF0000;" parent="1" vertex="1">

      <mxGeometry x="393" y="170" width="40" height="20" as="geometry"/>

    </mxCell>

  </root>

</mxGraphModel>







It is as if draw.io was wrong to reconstruct the XML





Other Test:

If I start a new blank diagram diretctly on draw.io, and insert a 2 text object and then set font size  to 22 pt (for first text) and 72 pt  (for second text),



draw.io generate this XML:

<mxGraphModel dx="1981" dy="745" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="827" pageHeight="1169" math="0" shadow="0">


  <root>

    <mxCell id="0"/>

    <mxCell id="1" parent="0"/>

    <mxCell id="FLn3v0A-PvVL2j7I-hHo-1" value="&lt;font style=&quot;font-size: 22px&quot;&gt;Text&lt;/font&gt;" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;" parent="1" vertex="1">

      <mxGeometry x="20" y="20" width="40" height="20" as="geometry"/>

    </mxCell>

    <mxCell id="FLn3v0A-PvVL2j7I-hHo-2" value="&lt;font style=&quot;font-size: 72px&quot;&gt;Text&lt;/font&gt;" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;" parent="1" vertex="1">

      <mxGeometry x="20" y="60" width="40" height="20" as="geometry"/>

    </mxCell>

  </root>

</mxGraphModel>




If I cut and paste thie XML into grafana flowchart I see :











(Sorry for black text )





The version of draw.io is:


I try with chrome : Versione 75.0.3770.90 (Build ufficiale) (a 64 bit)

and Mozilla firefox: 67.0.3 (64 bit)



My O.S is Linux: Ubuntu 18.04.2 LTS bionic







Sorry for my bad english !!!

I'm italian !!!





br
Alfredo




---- Attivato lun, 24 giu 2019 00:00:13 +0200 Arnaud GENTY <notifications@github.com> ha scritto ----



Hi,
 First, thx again for your feedback
 I dont know why but in your value in xml, i have
 value="<font color="#ff0000" style="font-size: 7px">Text</font>"
If i add text in in empty model, i have in xml :
 value="Text" and its works for me.
I need more test to understand why
 https://user-images.githubusercontent.com/47012725/59982446-c2020200-9612-11e9-8ea6-abe74de248f5.png
Try this model :
 1Zbfb4IwEMf/Gh6XQGtUHoVNl+zHw3Rx2VtDT2gslNUq4F+/Iu2EkSWLDxvyQLhPr3e9+x4BB4dpuZAkT54EBe4gl5YOvnUQGmGk7zWoGjCZjhsQS0Yb5J3Bkh3BQNfQPaOw6zgqIbhieRdGIssgUh1GpBRF120jeDdrTmLogWVEeJ+uGVVJQ6docub3wOLEZvbGfrOSEutsKtklhIqihfCd486c+tl1cCiFUB1kF9IyBF731PariTf/nfPX+SVk6oL9b69o+x6s1kDxc+U/sofjy8eNCXogfG/atIJSmTJVZXunaoiDRKVcA08/7pQUWwgFF1KTTGTaM9gwzr8hwlmcaTPShwbNgwNIxbQqM7OQMkrrNEGRMAXLnER1zkKPoGZS7DMKdQFuHV5kyswVHhnbpnMQns9dfWneb5QtU+eGsoX6jTu3bwEiBSUrbZst2DcDYN6AkTGL8zhZlLQmyY4NMQMcfwX+UTzNjX6XS4uuVVr3X6TFHWn9QUuLr1RaNB6AtB4etLaja9UWDUHbyR9re+KtD77xa/1Bnfgn

**Comment by algenty** [comment] 2019-06-24 08:11
grazie mille Alfredo, parlo italiano un poco,
3 years in school but i forgotten.
my englih is powerless too.
there are still a bug into plugin to render it, i'll try to fix it.
You know how to bypass this bug now.

BG
Arnaud

**Comment by cicciopizza** [comment] 2019-06-24 08:23
Wowwww  il mondo è piccolo !!! 





I work on monitoring systems ... and I use a lot of graphana



I use a lot in python but more for interfacing with data reading devices





As for the question of draw.io at the moment nothing comes to mind of fast.



When i have some time i will try to see if there is any option on drwa.io to get a "cleaner" XML





let's keep up to date ...







Ciaooo

 Alfredo







---- Attivato lun, 24 giu 2019 10:11:33 +0200 Arnaud GENTY <notifications@github.com> ha scritto ----



grazie mille Alfredo, parlo italiano un poco,
 3 years in school but i forgotten.
 my englih is powerless too.
 there are still a bug into plugin to render it, i'll try to fix it.
 You know how to bypass this bug now.
BG
 Arnaud

**Comment by algenty** [comment] 2019-09-24 18:38
Hi @cicciopizza 
You're right, i found a issue when Formatted Text is checked in draw.io
see

**Closed** 2019-10-03 05:30 UTC
Labels: Fixed
