### ISSUE TITLE
Inspector "Apply changes" button absence

### ISSUE THREAD

**Issue by mikle-a** [algenty/grafana-flowcharting#104] opened 2020-01-08 19:16 UTC
Hi there!

I'm trying to change object id using inspect tab as described [here](https://github.com/algenty/flowcharting-repository/blob/master/INSPECT.md). Unfortunately, "Apply changes" button does not appear, no matter what I do.

Here is an example in the attached screenshot: I've changed id 10 to 11, but there is still no button:
![image](https://user-images.githubusercontent.com/18206793/72008128-3412ff00-3264-11ea-8679-e0899ac01476.png)

Tried different grafana versions from 5.1 up to 6.4.

**Comment by algenty** [comment] 2020-01-09 18:20
need to investigate

**Comment by mikle-a** [comment] 2020-01-10 14:54
Do you need any kind of additional information from my side?

**Comment by tbaczynski** [comment] 2020-01-13 10:58
Duplicate of #58

**Comment by algenty** [comment] 2020-01-24 15:29
Fixed in 0.6.1.
Release in progress
https://github.com/grafana/grafana-plugin-repository/pull/556
Put a health to speed it up ;)

**Comment by algenty** [comment] 2020-01-27 09:19
Released !!

**Closed by algenty** 2020-01-27 09:19 UTC
